# Generated by Django 5.2.7 on 2026-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entidade', models.CharField(max_length=100)),
                ('Morada', models.CharField(max_length=255)),
                ('CodigoPostal', models.CharField(max_length=20)),
                ('Localidade', models.CharField(max_length=100)),
                ('Dicofre', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
