# Generated by Django 5.2.7 on 2026-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmain', '0002_moradas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moradas',
            name='Localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
