# Generated by Django 5.1.6 on 2025-10-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(help_text='Nome do fabricante da carta', max_length=50, verbose_name='Fabricante')),
                ('data_rececao', models.DateField(blank=True, help_text='Data de receção da carta', null=True, verbose_name='Data de receção')),
                ('b_type', models.CharField(help_text='Tipo de carta', max_length=20, verbose_name='Tipo de carta')),
                ('part_number', models.CharField(help_text='Model number', max_length=20, verbose_name='Model number')),
                ('serial_number', models.CharField(help_text='Número de série da carta', max_length=20, verbose_name='Número de série')),
                ('descricao', models.CharField(help_text='Descrição da carta', max_length=50, verbose_name='Descrição')),
                ('estado', models.CharField(help_text='Estado da carta', max_length=5, verbose_name='Estado')),
                ('projeto', models.CharField(help_text='Projeto associado à carta', max_length=50, verbose_name='Projeto')),
                ('sistema', models.CharField(help_text='Sistema associado à carta', max_length=50, verbose_name='Sistema')),
                ('localizacao', models.CharField(help_text='Localização física da carta', max_length=100, verbose_name='Localização')),
                ('equipamento', models.CharField(help_text='Equipamento onde a carta está instalada', max_length=20, verbose_name='Equipamento')),
                ('subrack', models.CharField(help_text='Subrack onde a carta está instalada', max_length=10, verbose_name='Subrack')),
                ('slot', models.CharField(help_text='Slot onde a carta está instalada', max_length=2, verbose_name='Slot')),
                ('porto', models.CharField(help_text='Porto onde a carta está instalada', max_length=2, verbose_name='Porto')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', max_length=200, verbose_name='Observações')),
            ],
            options={
                'ordering': ['fabricante', 'part_number', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='hist_cartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('utilizador', models.CharField(max_length=50)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartas.cartas')),
            ],
            options={
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
