# Generated by Django 5.1.6 on 2025-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição da carta', max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='equipamento',
            field=models.CharField(blank=True, help_text='Equipamento onde a carta está instalada', max_length=20, null=True, verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Localização física da carta', max_length=100, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='porto',
            field=models.CharField(blank=True, help_text='Porto onde a carta está instalada', max_length=2, null=True, verbose_name='Porto'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='projeto',
            field=models.CharField(blank=True, help_text='Projeto associado à carta', max_length=50, null=True, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='sistema',
            field=models.CharField(blank=True, help_text='Sistema associado à carta', max_length=50, null=True, verbose_name='Sistema'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='slot',
            field=models.CharField(blank=True, help_text='Slot onde a carta está instalada', max_length=2, null=True, verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='subrack',
            field=models.CharField(blank=True, help_text='Subrack onde a carta está instalada', max_length=10, null=True, verbose_name='Subrack'),
        ),
    ]
