# Generated by Django 5.1.6 on 2025-10-22 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0002_alter_cartas_descricao_alter_cartas_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas',
            name='data_rececao',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Data de receção da carta', null=True, verbose_name='Data de receção'),
        ),
        migrations.AlterField(
            model_name='cartas',
            name='fabricante',
            field=models.CharField(blank=True, help_text='Nome do fabricante da carta', max_length=50, null=True, verbose_name='Fabricante'),
        ),
    ]
