# Generated by Django 5.1.6 on 2025-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sdados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISID', models.CharField(max_length=10, unique=True)),
                ('ISID_name', models.CharField(max_length=100)),
                ('Service_type', models.CharField(max_length=100)),
                ('Mux_mode', models.CharField(blank=True, max_length=100)),
                ('Service_status', models.CharField(blank=True, max_length=100)),
                ('Connect_type', models.CharField(blank=True, max_length=100)),
                ('VLAN_translation', models.CharField(blank=True, max_length=100)),
                ('Cliente', models.CharField(max_length=100)),
                ('Notas', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['ISID'],
            },
        ),
        migrations.CreateModel(
            name='sterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misid', models.CharField(max_length=15)),
                ('Local', models.CharField(max_length=100)),
                ('Morada', models.CharField(blank=True, default='', max_length=100)),
                ('Cod_Postal', models.CharField(blank=True, default='', max_length=100)),
                ('Equipamento', models.CharField(max_length=100)),
                ('SAP', models.CharField(max_length=100)),
                ('Notas', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['SAP'],
            },
        ),
    ]
