# Generated by Django 5.1.6 on 2025-06-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sterm',
            name='misid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdados.sdados'),
        ),
    ]
