# Generated by Django 5.2.7 on 2025-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0003_sdados_created_at_sterm_data_actualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdados',
            name='estado',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AddField(
            model_name='sterm',
            name='estado',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
