# Generated by Django 5.2.7 on 2025-11-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0004_sdados_estado_sterm_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdados',
            name='Service_status',
        ),
    ]
