# Generated by Django 5.2.7 on 2025-11-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0005_remove_sdados_service_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdados',
            options={'ordering': ['isid']},
        ),
        migrations.AlterModelOptions(
            name='sterm',
            options={'ordering': ['sap']},
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='Connect_type',
            new_name='connect_type',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='ISID',
            new_name='isid',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='ISID_name',
            new_name='isid_name',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='Mux_mode',
            new_name='mux_mode',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='Notas',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='Service_type',
            new_name='service_type',
        ),
        migrations.RenameField(
            model_name='sdados',
            old_name='VLAN_translation',
            new_name='vlan_translation',
        ),
        migrations.RenameField(
            model_name='sterm',
            old_name='Cod_Postal',
            new_name='cod_postal',
        ),
        migrations.RenameField(
            model_name='sterm',
            old_name='Equipamento',
            new_name='equipamento',
        ),
        migrations.RenameField(
            model_name='sterm',
            old_name='Local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='sterm',
            old_name='Morada',
            new_name='morada',
        ),
        migrations.RenameField(
            model_name='sterm',
            old_name='Notas',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='sterm',
            old_name='SAP',
            new_name='sap',
        ),
    ]
