# Generated by Django 5.2.7 on 2025-11-12 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0006_alter_sdados_options_alter_sterm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdados',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
