# Generated by Django 5.2.7 on 2025-11-12 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0007_alter_sdados_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdados',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sterm',
            name='data_actualizacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
