# Generated by Django 5.2.7 on 2025-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0008_alter_sdados_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sterm',
            name='misid',
            field=models.CharField(max_length=10),
        ),
    ]
