# Generated by Django 5.2.7 on 2025-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0009_alter_sterm_misid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdados',
            name='created_at',
            field=models.DateField(),
        ),
    ]
