# Generated by Django 5.2.7 on 2025-11-18 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdados', '0010_alter_sdados_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdados',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
