# Generated by Django 5.1.6 on 2025-03-13 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serv_dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISID', models.CharField(max_length=10)),
                ('ISID_name', models.CharField(max_length=100)),
                ('Service_type', models.CharField(max_length=100)),
                ('Mux_mode', models.CharField(max_length=100)),
                ('Service_status', models.CharField(max_length=100)),
                ('Connect_type', models.CharField(max_length=100)),
                ('VLAN_translation', models.CharField(max_length=100)),
                ('Cliente', models.CharField(max_length=100)),
                ('Notas', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ISID'],
            },
        ),
        migrations.CreateModel(
            name='terminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local', models.CharField(max_length=100)),
                ('Morada', models.CharField(max_length=100)),
                ('Cod_Postal', models.CharField(max_length=100)),
                ('dicofre', models.CharField(max_length=6)),
                ('Equipamento', models.CharField(max_length=100)),
                ('SAP', models.CharField(max_length=100)),
                ('Notas', models.CharField(max_length=100)),
                ('main_isid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.serv_dados')),
            ],
            options={
                'ordering': ['main_isid'],
            },
        ),
    ]
