# Generated by Django 5.1.6 on 2025-06-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serv_dados',
            name='ISID',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='serv_dados',
            name='Notas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='terminacao',
            name='main_isid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='dados.serv_dados'),
        ),
    ]
