# Generated by Django 5.1.6 on 2025-06-16 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_alter_serv_dados_isid_alter_serv_dados_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminacao',
            name='main_isid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.serv_dados'),
        ),
    ]
