# Generated by Django 5.1.6 on 2025-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_alter_terminacao_main_isid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminacao',
            name='Notas',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
