# Generated by Django 5.1.6 on 2025-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_alter_terminacao_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminacao',
            name='main_isid',
            field=models.IntegerField(),
        ),
    ]
