# Generated by Django 5.1.6 on 2025-03-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ligafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, help_text='Referência', max_length=20, null=True, verbose_name='Referência')),
                ('cliente', models.CharField(blank=True, help_text='Cliente', max_length=100, null=True, verbose_name='Cliente')),
                ('dist_iet', models.DecimalField(blank=True, decimal_places=3, help_text='Distância km IET50', max_digits=6, null=True, verbose_name='Distância km IET50')),
                ('dist_optica', models.DecimalField(blank=True, decimal_places=3, help_text='Distância km ótica', max_digits=6, null=True, verbose_name='Distância km ótica')),
                ('data_pedido', models.DateField(blank=True, help_text='Data pedido', null=True, verbose_name='Data pedido')),
                ('data_entrega', models.DateField(blank=True, help_text='Data Entrega', null=True, verbose_name='Data Entrega')),
                ('estado', models.CharField(blank=True, help_text='Estado', max_length=20, null=True, verbose_name='Estado')),
                ('local_a', models.CharField(blank=True, help_text='Local A', max_length=150, null=True, verbose_name='Local A')),
                ('equipa_a', models.CharField(blank=True, help_text='Equipamento A', max_length=20, null=True, verbose_name='Equipamento A')),
                ('slot_a', models.CharField(blank=True, help_text='Slot A', max_length=20, null=True, verbose_name='Slot A')),
                ('porta_a', models.CharField(blank=True, help_text='Porta A', max_length=20, null=True, verbose_name='Porta A')),
                ('local_b', models.CharField(blank=True, help_text='Local B', max_length=150, null=True, verbose_name='Local B')),
                ('equipa_b', models.CharField(blank=True, help_text='Equipamento B', max_length=20, null=True, verbose_name='Equipamento B')),
                ('slot_b', models.CharField(blank=True, help_text='Slot B', max_length=20, null=True, verbose_name='Slot B')),
                ('porta_b', models.CharField(blank=True, help_text='Porta B', max_length=20, null=True, verbose_name='Porta B')),
                ('observacoes', models.TextField(blank=True, help_text='Observações', max_length=150, null=True, verbose_name='Observações')),
            ],
            options={
                'ordering': ['referencia'],
            },
        ),
    ]
