# Generated by Django 5.1.6 on 2025-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligafo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligafo',
            name='encomenda',
            field=models.CharField(blank=True, help_text='Encomenda', max_length=20, null=True, verbose_name='Encomenda'),
        ),
    ]
