# Generated by Django 5.1.6 on 2025-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligafo', '0002_ligafo_encomenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligafo',
            name='cliente',
            field=models.CharField(help_text='Cliente', max_length=100, verbose_name='Cliente'),
        ),
    ]
