# Generated by Django 5.1.6 on 2025-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circ_Foe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_circ', models.CharField(help_text='Número/referência de Circuito', max_length=15, verbose_name='Número de circuito')),
                ('ref_enc', models.CharField(default='', help_text='Referência de encomenda', max_length=20, verbose_name='Referência de encomenda')),
                ('cliente', models.TextField(default='', help_text='Nome do cliente', max_length=150, verbose_name='Cliente')),
                ('dist_km', models.DecimalField(decimal_places=3, default=0, help_text='Distância km', max_digits=6, verbose_name='Distância km')),
                ('dist_optica', models.DecimalField(decimal_places=3, default=0, help_text='Distância Óptica', max_digits=6, verbose_name='Distância Óptica')),
                ('data_obj', models.DateField(blank=True, help_text='Data Objetivo', null=True, verbose_name='Data Objetivo')),
                ('data_entrega', models.DateField(blank=True, help_text='Data de entrega', null=True, verbose_name='Data de entrega')),
                ('data_ocupa', models.DateField(blank=True, help_text='Data de ocupação', null=True, verbose_name='Data de ocupação')),
                ('estado', models.TextField(default='Inst', help_text='Estado do circuito', max_length=20, verbose_name='Estado do circuito')),
                ('local_a', models.TextField(default='', help_text='Local A', max_length=150, verbose_name='Local A')),
                ('ligacao_a', models.TextField(default='', help_text='Ligação local A', max_length=20, verbose_name='Ligação local A')),
                ('local_b', models.TextField(default='', help_text='Local B', max_length=150, verbose_name='Local B')),
                ('ligacao_b', models.TextField(default='', help_text='Ligação local B', max_length=20, verbose_name='Ligação local B')),
                ('observacoes', models.TextField(default='', help_text='Observações', max_length=250, verbose_name='Observações')),
                ('notas', models.TextField(default='', help_text='Notas', max_length=250, verbose_name='Notas')),
            ],
            options={
                'ordering': ['n_circ'],
            },
        ),
    ]
