# Generated by Django 5.1.6 on 2025-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='referencia',
            field=models.CharField(help_text='Referência', max_length=20, verbose_name='Referência'),
        ),
    ]
