# Generated by Django 5.1.6 on 2025-03-26 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0002_alter_circfoe_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='cliente',
            field=models.CharField(help_text='Cliente', max_length=30, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='data_entrega',
            field=models.DateField(blank=True, default='2025-12-31', help_text='Data entrega', verbose_name='Data entrega'),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='data_ocupa',
            field=models.DateField(blank=True, default='2025-12-31', help_text='Data ocupação', verbose_name='Data ocupação'),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='dist_km',
            field=models.DecimalField(blank=True, decimal_places=3, default='000.000', help_text='Distância km IET50', max_digits=6, verbose_name='Distância Kilométrica'),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='dist_optica',
            field=models.DecimalField(blank=True, decimal_places=3, default='000.000', help_text='Distância km ótica', max_digits=6, verbose_name='Distância km ótica'),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='ligacao_a',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='ligacao_b',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='observacoes',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='Observações', max_length=150, verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referência', max_length=20, verbose_name='Referência'),
        ),
    ]
