# Generated by Django 5.1.6 on 2025-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0003_alter_circfoe_cliente_alter_circfoe_data_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='tipo_ocupa',
            field=models.CharField(blank=True, help_text='Tipo Ocupação', max_length=20, verbose_name='Tipo Ocupação'),
        ),
    ]
