# Generated by Django 5.1.6 on 2025-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0004_alter_circfoe_tipo_ocupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='data_obj',
            field=models.DateField(blank=True, help_text='Data objectivo', verbose_name='Data objectivo'),
        ),
    ]
