# Generated by Django 5.2.7 on 2025-10-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0005_alter_circfoe_data_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='encomenda',
            field=models.CharField(blank=True, default='ref encomenda', help_text='Encomenda', max_length=20, verbose_name='Encomenda'),
        ),
    ]
