# Generated by Django 5.2.7 on 2025-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0006_alter_circfoe_encomenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='ligacao_a',
            field=models.CharField(blank=True, default='ODF', max_length=20),
        ),
        migrations.AlterField(
            model_name='circfoe',
            name='ligacao_b',
            field=models.CharField(blank=True, default='ODF', max_length=20),
        ),
    ]
