# Generated by Django 5.2.7 on 2025-10-31 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0007_alter_circfoe_ligacao_a_alter_circfoe_ligacao_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='circfoe',
            name='create_user',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='circfoe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circfoe',
            name='update_user',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='circfoe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
