# Generated by Django 5.2.7 on 2026-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foe', '0008_circfoe_create_user_circfoe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circfoe',
            name='encomenda',
            field=models.CharField(blank=True, default='ref encomenda', help_text='Encomenda', max_length=30, verbose_name='Encomenda'),
        ),
    ]
