# Generated by Django 5.0.6 on 2024-07-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0002_circuitos_morada_ptr2_circuitos_outras_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitos',
            name='Estado_Cct',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='circuitos',
            name='Morada_PTR1',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Morada_PTR2',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Outras_Ref',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Propriedade',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Uset_Cct',
            field=models.TextField(default='', max_length=150),
        ),
    ]
