# Generated by Django 5.1.6 on 2025-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0002_alter_circuitos_user_cct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='N_Circuito',
            field=models.CharField(blank=True, help_text='Numero/referencia de Circuito', max_length=20, verbose_name='Número de circuito'),
        ),
    ]
