# Generated by Django 5.1.6 on 2025-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0003_alter_circuitos_n_circuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='Data_Inst',
            field=models.DateField(blank=True),
        ),
    ]
