# Generated by Django 5.0.6 on 2024-07-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0003_circuitos_estado_cct_circuitos_morada_ptr1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitos',
            old_name='Propriedade',
            new_name='Propriedade_Cct',
        ),
        migrations.RenameField(
            model_name='circuitos',
            old_name='Uset_Cct',
            new_name='User_Cct',
        ),
    ]
