# Generated by Django 5.1.6 on 2025-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0004_alter_circuitos_data_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='Data_Inst',
            field=models.DateField(blank=True, null=True),
        ),
    ]
