# Generated by Django 5.1.6 on 2025-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0004_rename_propriedade_circuitos_propriedade_cct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitos',
            name='Cod_Post_PTR1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Cod_Post_PTR2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Data_Activ',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Equip_PTR1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Equip_PTR2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Estado_Cct',
            field=models.TextField(default='Definido', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Interface_PTR1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Interface_PTR2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Morada_PTR1',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Morada_PTR2',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='N_Circuito',
            field=models.CharField(help_text='Numero/referencia de Circuito', max_length=20, verbose_name='Número de circuito'),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Outras_Ref',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Propriedade_Cct',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Slot_PTR1',
            field=models.CharField(blank=True, default='---', max_length=5),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Slot_PTR2',
            field=models.CharField(blank=True, default='---', max_length=5),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Trib_PTR1',
            field=models.CharField(blank=True, default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='circuitos',
            name='Trib_PTR2',
            field=models.CharField(blank=True, default='---', max_length=10),
        ),
    ]
