# Generated by Django 5.1.6 on 2025-10-08 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0005_alter_circuitos_data_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circuitos',
            name='update_user',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='circuitos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
