# Generated by Django 5.1.6 on 2025-10-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0006_circuitos_created_at_circuitos_update_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitos',
            name='create_user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
